[tool.poetry]
name = "mw_url_shortener"
version = "0.0.2"
description = "A URL shortener API webserver"
authors = ["Matthew Willcockson <matthew@willcockson.family>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/mawillcockson/mw_url_shortener"

[tool.poetry.dependencies]
python = ">=3.6.9,<3.10.0"
fastapi = {version = "^0.61.2", extras = ["all"]}
pony = "^0.7.14"
python-dateutil = "^2.8.1"
python-jose = "^3.2.0"
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
questionary = "^1.8.1"
decli = "^0.5.2"
importlib-metadata = {version = "^2.1.0", python = "<3.8"} # NOTE:FUTURE tox depends on <3.0.0

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.1"
black = "^20.8b1"
mypy = "^0.790"
isort = "^5.6.4"
tox = "^3.20.1"

[tool.poetry.scripts]
mw_url_shortener = "mw_url_shortener.console:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
