print(f"imported mw_url_shortener.console as {__name__}")
"""
The main cli frontend for the program

Primarily uses: https://github.com/Woile/decli
"""
from decli import cli
from . import config, __version__
from .config import CommonSettings, ServerSettings
from typing import Callable, Union, Optional
import sys
import argparse
from argparse import ArgumentTypeError, Namespace
from pathlib import Path
from .random_chars import unsafe_random_chars


class ArgumentValidationError(ArgumentTypeError, TypeError):
    "subclasses both argparse.ArgumentTypeError and TypeError"
    pass


class OpenableFileMeta(type):
    "Only here to make OpenableFile a callable class"
    def __call__(self, filename: Union[Path, str, type(None)]) -> Path:
        "checks that the filename is a valid path, and returns it"
        path = Path(filename).resolve()
        if not path.is_file():
            raise ArgumentValidationError(f"'{path}' is not a file")

        try:
            file = path.open(mode="rb")
        except OSError as err:
            raise ArgumentValidationError(f"cannot open '{path}'")
        finally:
            file.close()

        return path


class OpenableFile(metaclass=OpenableFileMeta):
    "Will only take a file that's able to be read"
    pass


def raise_not_implemented_gen(message: str) -> Callable[[], None]:
    """
    Make a function that will raise a NotImplemented error with a custom
    message
    """
    def not_implemented() -> None:
        raise NotImplementedError(message)

    return not_implemented


def server_run(args: Namespace) -> None:
    """
    Obtains all configuration information for the server, then runs the server
    """
    # NOTE: import here so that it's not imported when console is imported and
    # run, to keep load times down
    import uvicorn
    from . import server
    if args.env_file:
        settings = ServerSettings(_env_file=args.env_file, **vars(args))
    else:
        settings = ServerSettings.from_orm(args)

    print(f"\nsettings:\n{settings}\n")
    server.app.state.settings = settings
    # NOTE:BUG Is this necessary?
    # Are the settings states shared to mounted apps?
    # Do I need to manage updates to that state in both places?
    #server.api_app_v1.state.settings = settings
    server.app.mount(f"/{settings.api_key}", server.api_app_v1)

    # NOTE:IMPROVEMENT This needs to be updated to programmatically find the
    # appropriate name of the module and function to run, istead of hardcoding
    # it to mw_url_shortener.server:app
    uvicorn.run("mw_url_shortener.server:app", reload=settings.reload, root_path=f"/{settings.root_path}")


interface_spec = {
    "description": "Runs, creates, and interacts with a URL shortener",
    "add_help": True,
    "allow_abbrev": True,
    "arguments": [
        {
            "name": "--version",
            "action": "version",
            "version": f"%(prog)s {__version__}",
            "help": "prints the version",
        },
        {
            "name": ["-c", "--env-file"],
            "type": OpenableFile,
            "default": None,
            "help": "config file in python-dotenv format",
        },
    ],
    "subcommands": {
        "title": "subcommands",
        "description": "use --help on a subcommand to see its options",
        "commands": [
            {
                "name": "server",
                "func": server_run,
                "arguments": [
                    {
                        "name": ["--reload"],
                        "help": "Watch the server files and reload the server when those files change",
                        "action": "store_true",
                        "default": argparse.SUPPRESS,
                        "group": "development",
                    },
                    {
                        "name": ["--api-key"],
                        "help": "Sets a prefix for the API URL; leave blank for autogenerated",
                        "default": argparse.SUPPRESS,
                        "const": unsafe_random_chars(10),
                        "nargs": "?",
                    },
                    {
                        "name": ["--root-path"],
                        "help": "Sets an app-wide prefix (e.g. domain.test/example_root_path/api_key/v1/users)",
                        "default": argparse.SUPPRESS,
                    },
                ],
            },
            {
                "name": "client",
                "func": raise_not_implemented_gen("No client command")
            },
            {
                "name": "config",
                "func": raise_not_implemented_gen("No config command")
            },
        ],
    },
}

def main() -> None:
    """
    Parses the cli arguments and runs the appropriate commands
    """
    parser = cli(interface_spec)
    args = parser.parse_args()

    if "func" not in args:
        # No subcommand was specified:
        # $ mw_url_shortener
        parser.print_usage()
        sys.exit("Hint: try the 'config' sub-command")

    args.func(args=args)


if __name__ == "__main__":
    main()
